__author__ = 'Parsa Darbandsari <parsa.darbandsari@outlook.com>'
__version__ = '1.0'
NEW_DIRECTORY_COMMAND = "nwdir"
REMOVE_DIRECTORY_COMMAND = "rmvdir"
EXECUTE_COMMAND = "/:"
CHNAGE_DIRECTORY_COMMAND = "goto"
GO_TO_PARENT_DIRECTORY_COMMAND = "goback"
LIST_COMMAND = "list"
REMOVE_FILE_COMMAND = "rmvfile"
EXIT_COMMAND = 'exit'
CLEARSCREEN_COMMAND = 'cls'
COMMAND_LIST = [CLEARSCREEN_COMMAND, EXIT_COMMAND, REMOVE_FILE_COMMAND, LIST_COMMAND,
                GO_TO_PARENT_DIRECTORY_COMMAND, CHNAGE_DIRECTORY_COMMAND, EXECUTE_COMMAND,
                REMOVE_DIRECTORY_COMMAND, NEW_DIRECTORY_COMMAND]